name: CI/CD Pipeline Test

on:
  push:
    branches:
      - main

jobs:
  unit-tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy
        working-directory: app

      - name: Run Tests
        run: go test ./...
        working-directory: app

  containerize: 
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t gnanieswar195/k8s-github-actions:latest .
        working-directory: app

      - name: Push Docker Image
        run: docker push gnanieswar195/k8s-github-actions:latest

  k8s-deploy:  
    needs: containerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes Access
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl get nodes
          kubectl apply -f k8s/

